# Generated by Django 5.2.7 on 2026-01-15 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("holiday", "📌 Feriado"),
                            ("exam", "📝 Prova/Avaliação"),
                            ("graduation", "🎓 Formatura"),
                            ("cultural", "🎉 Evento Cultural"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="schools.school",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento do Calendário",
                "verbose_name_plural": "Eventos do Calendário",
                "db_table": "events_calendarevent",
                "ordering": ["date"],
            },
        ),
    ]
