# Generated by Django 5.2.7 on 2026-01-31 22:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
            },
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="date",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="end_date",
            field=models.DateField(null=True, verbose_name="End Date"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("holiday", "📌 Holiday"),
                    ("exam", "📝 Exam/Assessment"),
                    ("graduation", "🎓 Graduation"),
                    ("cultural", "🎉 Cultural Event"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["school", "start_date"], name="events_cale_school__5253a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["event_type"], name="events_cale_event_t_66573a_idx"),
        ),
    ]
