# Generated by Django 5.2.7 on 2025-12-18 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_agente', models.CharField(default='ativo', max_length=20)),
                ('interacoes_hoje', models.IntegerField(default=0)),
                ('documentos_upload', models.IntegerField(default=0)),
                ('faqs_criadas', models.IntegerField(default=0)),
                ('leads_capturados', models.IntegerField(default=0)),
                ('taxa_resolucao', models.IntegerField(default=0)),
                ('novos_hoje', models.IntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='schools.escola')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
