# Generated by Django 5.2.7 on 2026-01-31 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardCache",
            fields=[
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dashboard_cache",
                        serialize=False,
                        to="schools.school",
                    ),
                ),
                ("leads_total", models.IntegerField(default=0)),
                ("leads_new", models.IntegerField(default=0)),
                ("leads_in_contact", models.IntegerField(default=0)),
                ("leads_qualified", models.IntegerField(default=0)),
                ("leads_converted", models.IntegerField(default=0)),
                ("leads_lost", models.IntegerField(default=0)),
                ("conversion_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("leads_by_origin", models.JSONField(default=dict)),
                ("contacts_total", models.IntegerField(default=0)),
                ("contacts_active", models.IntegerField(default=0)),
                ("contacts_inactive", models.IntegerField(default=0)),
                ("tickets_total", models.IntegerField(default=0)),
                ("tickets_open", models.IntegerField(default=0)),
                ("tickets_closed", models.IntegerField(default=0)),
                ("events_total", models.IntegerField(default=0)),
                ("events_upcoming", models.IntegerField(default=0)),
                ("faqs_total", models.IntegerField(default=0)),
                ("faqs_active", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("update_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Dashboard Cache",
                "db_table": "dashboard_cache",
            },
        ),
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[("daily", "Diário"), ("monthly", "Mensal")],
                        default="daily",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True, verbose_name="Data")),
                ("leads_total", models.IntegerField(default=0)),
                ("leads_new", models.IntegerField(default=0)),
                ("leads_in_contact", models.IntegerField(default=0)),
                ("leads_qualified", models.IntegerField(default=0)),
                ("leads_converted", models.IntegerField(default=0)),
                ("leads_lost", models.IntegerField(default=0)),
                ("conversion_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("leads_by_origin", models.JSONField(default=dict)),
                ("contacts_total", models.IntegerField(default=0)),
                ("contacts_active", models.IntegerField(default=0)),
                ("contacts_inactive", models.IntegerField(default=0)),
                ("tickets_total", models.IntegerField(default=0)),
                ("tickets_open", models.IntegerField(default=0)),
                ("tickets_closed", models.IntegerField(default=0)),
                ("events_total", models.IntegerField(default=0)),
                ("events_upcoming", models.IntegerField(default=0)),
                ("faqs_total", models.IntegerField(default=0)),
                ("faqs_active", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_snapshots",
                        to="schools.school",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Snapshot",
                "verbose_name_plural": "Dashboard Snapshots",
                "db_table": "dashboard_snapshots",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["school", "snapshot_date"], name="dashboard_s_school__ab3904_idx"
                    )
                ],
                "unique_together": {("school", "snapshot_type", "snapshot_date")},
            },
        ),
    ]
