# Generated by Django 5.2.7 on 2025-12-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("total_interacoes", models.IntegerField(default=0)),
                ("interacoes_hoje", models.IntegerField(default=0)),
                ("leads_capturados", models.IntegerField(default=0)),
                ("tickets_abertos", models.IntegerField(default=0)),
                ("tempo_medio_resposta", models.CharField(default="0min", max_length=20)),
                ("taxa_satisfacao", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("taxa_conversao", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "status_agente",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("ocupado", "Ocupado"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("n8n_workflow_id", models.CharField(blank=True, max_length=100)),
                ("n8n_execution_id", models.CharField(blank=True, max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_metrics",
                        to="schools.escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Metrics",
                "verbose_name_plural": "Dashboard Metrics",
                "ordering": ["-atualizado_em"],
            },
        ),
        migrations.CreateModel(
            name="InteracaoN8N",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensagem", "Mensagem"),
                            ("lead", "Lead Capturado"),
                            ("ticket", "Ticket Criado"),
                            ("contato", "Contato Registrado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("dados", models.JSONField(default=dict)),
                ("n8n_workflow_id", models.CharField(blank=True, max_length=100)),
                ("n8n_execution_id", models.CharField(blank=True, max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoes_n8n",
                        to="schools.escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interação N8N",
                "verbose_name_plural": "Interações N8N",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.DeleteModel(
            name="Dashboard",
        ),
        migrations.AddIndex(
            model_name="dashboardmetrics",
            index=models.Index(
                fields=["escola", "-atualizado_em"], name="dashboard_d_escola__b7bef7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interacaon8n",
            index=models.Index(
                fields=["escola", "-criado_em"], name="dashboard_i_escola__fe1366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interacaon8n",
            index=models.Index(fields=["tipo", "-criado_em"], name="dashboard_i_tipo_3f7b63_idx"),
        ),
    ]
