# Generated by Django 5.2.7 on 2026-01-15 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Nome Completo"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="Data de Nascimento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Ativo"), ("inactive", "Inativo")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("website", "Site"),
                            ("phone_call", "Telefone"),
                            ("in_person", "Presencial"),
                            ("email", "Email"),
                            ("referral", "Indicação"),
                        ],
                        default="whatsapp",
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "last_interaction_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Última Interação"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("tags", models.CharField(blank=True, max_length=500, verbose_name="Tags")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_contacts",
                        to="schools.school",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato WhatsApp",
                "verbose_name_plural": "Contatos WhatsApp",
                "db_table": "contacts_whatsappcontact",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "status"], name="contacts_wh_school__0964e4_idx"
                    ),
                    models.Index(fields=["phone"], name="contacts_wh_phone_495794_idx"),
                    models.Index(fields=["email"], name="contacts_wh_email_4f2a9a_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email__isnull", False), ("phone__isnull", False), _connector="OR"
                        ),
                        name="whatsappcontact_must_have_contact_info",
                    )
                ],
            },
        ),
    ]
