# Generated by Django 5.2.7 on 2025-12-18 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('site', 'Site'), ('telefone', 'Telefone'), ('presencial', 'Presencial'), ('email', 'Email'), ('indicacao', 'Indicação')], default='whatsapp', max_length=20)),
                ('ultima_interacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='schools.escola')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contato Geral',
                'verbose_name_plural': 'Contatos Gerais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['escola', 'status'], name='contacts_co_escola__f131f0_idx'), models.Index(fields=['criado_em'], name='contacts_co_criado__f137ed_idx'), models.Index(fields=['email'], name='contacts_co_email_77e91f_idx')],
            },
        ),
    ]
