# Generated by Django 5.2.7 on 2026-01-23 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faqs", "0001_initial"),
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(blank=True, verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("Admission", "Admission"),
                    ("Pricing", "Pricing"),
                    ("Uniform", "Uniform"),
                    ("Schedule", "Schedule"),
                    ("Documentation", "Documentation"),
                    ("Activities", "Activities"),
                    ("Meals", "Meals"),
                    ("Transport", "Transport"),
                    ("Pedagogical", "Pedagogical"),
                    ("General", "General"),
                ],
                max_length=100,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_faqs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=500, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
