# Generated by Django 5.2.7 on 2026-01-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("telephone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contact", "In Contact"),
                            ("qualified", "Qualified"),
                            ("conversion", "Conversion"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("site", "Site"),
                            ("whatsapp", "WhatsApp"),
                            ("recommendation", "Recommendation"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                        ],
                        default="whatsapp",
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                ("observations", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "interests",
                    models.JSONField(blank=True, default=dict, verbose_name="Interesses"),
                ),
                (
                    "contacted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Contatado em"),
                ),
                (
                    "converted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Convertido em"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="schools.school",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads_lead",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["school", "status"], name="leads_lead_school__2daced_idx"),
                    models.Index(fields=["email"], name="leads_lead_email_f663dc_idx"),
                ],
            },
        ),
    ]
