# Generated by Django 5.2.7 on 2025-12-18 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contact", "In Contact"),
                            ("qualified", "Qualified"),
                            ("conversion", "Conversion"),
                            ("lost", "Lost"),
                        ],
                        default="novo",
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("site", "Site"),
                            ("whatsapp", "WhatsApp"),
                            ("recommendation", "Recommendation"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("interests", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="schools.escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
