# Generated by Django 5.2.7 on 2026-01-15 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Gestor da Escola"),
                            ("operator", "Operador/Auxiliar"),
                            ("end_user", "Usuário Final (Cliente/Aluno)"),
                        ],
                        default="end_user",
                        help_text="Define as permissões do usuário",
                        max_length=20,
                        verbose_name="Nível de Acesso",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Usuário ativo no sistema", verbose_name="Ativo"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone de contato (especialmente para end_user)",
                        max_length=20,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="Data de Nascimento"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Escola vinculada (obrigatório para não-superusers)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="schools.school",
                        verbose_name="Escola",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuário Django vinculado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
                "db_table": "users_userprofile",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["school", "role"], name="users_userp_school__8a394c_idx"),
                    models.Index(
                        fields=["user", "is_active"], name="users_userp_user_id_efd302_idx"
                    ),
                ],
            },
        ),
    ]
