# Generated by Django 5.2.7 on 2025-12-18 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gestor', 'Gestor da Escola'), ('operador', 'Operador')], default='operador', help_text='Tipo de acesso do usuário', max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Usuário ativo no sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(help_text='Escola vinculada ao usuário', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='schools.escola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'indexes': [models.Index(fields=['escola', 'tipo'], name='users_perfi_escola__0c2dba_idx')],
            },
        ),
    ]
