# Generated by Django 5.2.7 on 2026-01-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Data de Nascimento"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Telefone de contato (especialmente para end_user)",
                max_length=20,
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Usuário ativo no sistema", verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Gestor da Escola"),
                    ("operator", "Operador/Auxiliar"),
                    ("end_user", "Usuário Final (Cliente/Aluno)"),
                ],
                default="end_user",
                help_text="Define as permissões do usuário",
                max_length=20,
                verbose_name="Nível de Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Escola vinculada (obrigatório para não-superusers)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="schools.school",
                verbose_name="Escola",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Usuário Django vinculado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__is_superuser", True), ("school__isnull", False), _connector="OR"
                ),
                name="school_required_for_non_superuser",
            ),
        ),
    ]
