# Generated by Django 5.2.7 on 2025-12-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in Progress', 'In_Progress'), ('pending', 'Pending'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='pending', max_length=15),
        ),
    ]
