# Generated by Django 5.2.7 on 2025-12-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Urgent', 'urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'open'), ('In Progress', 'in_Progress'), ('Pending', 'pending'), ('Closed', 'closed'), ('Resolved', 'resolved')], default='pending', max_length=15),
        ),
    ]
