# Generated by Django 5.2.7 on 2025-12-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(help_text='Nome da escola (só superuser pode alterar)', max_length=255)),
                ('cnpj', models.CharField(help_text='CNPJ da escola (só superuser pode alterar)', max_length=20, unique=True)),
                ('token_mensagens', models.CharField(blank=True, help_text='Token para mensagens (só superuser pode alterar)', max_length=40)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('sobre', models.TextField(blank=True)),
                ('niveis_ensino', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
