# Generated by Django 5.2.7 on 2026-01-15 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        help_text="School name (superuser only)",
                        max_length=255,
                        verbose_name="Nome da Escola",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        help_text="Brazilian CNPJ (superuser only)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tax ID must be exactly 14 digits (CNPJ)", regex="^\\d{14}$"
                            )
                        ],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "messaging_token",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp API token (superuser only)",
                        max_length=100,
                        verbose_name="Token de Mensagens",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, null=True, verbose_name="Site")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/logos/", verbose_name="Logo"
                    ),
                ),
                ("postal_code", models.CharField(max_length=10, verbose_name="CEP")),
                ("street_address", models.CharField(max_length=255, verbose_name="Endereço")),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "address_complement",
                    models.CharField(blank=True, max_length=255, verbose_name="Complemento"),
                ),
                ("about", models.TextField(blank=True, verbose_name="Sobre")),
                (
                    "teaching_levels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"elementary": true, "high_school": false}',
                        verbose_name="Níveis de Ensino",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
                "db_table": "schools_school",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tax_id"], name="schools_sch_tax_id_90a9cb_idx"),
                    models.Index(fields=["city", "state"], name="schools_sch_city_eac1bd_idx"),
                ],
            },
        ),
    ]
