# Generated by Django 5.2.7 on 2026-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="application_token",
            field=models.CharField(
                blank=True,
                help_text="Application API token (superuser only)",
                max_length=100,
                verbose_name="Token da Aplicação (SIGA | etc...)",
            ),
        ),
    ]
