# Generated by Django 5.2.7 on 2026-01-31 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("size", models.BigIntegerField(verbose_name="Tamanho (bytes)")),
                (
                    "mime_type",
                    models.CharField(
                        choices=[
                            ("application/pdf", "PDF"),
                            ("image/jpeg", "JPEG Image"),
                            ("image/png", "PNG Image"),
                            ("image/gif", "GIF Image"),
                            ("image/webp", "WebP Image"),
                            (
                                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                "Word Document",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                "Excel Spreadsheet",
                            ),
                            (
                                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                                "PowerPoint",
                            ),
                            ("text/plain", "Text File"),
                            ("text/csv", "CSV File"),
                            ("application/zip", "ZIP Archive"),
                        ],
                        max_length=100,
                        verbose_name="Tipo",
                    ),
                ),
                ("extension", models.CharField(max_length=10, verbose_name="Extensão")),
                (
                    "r2_key",
                    models.CharField(
                        help_text="Caminho único no bucket R2",
                        max_length=500,
                        unique=True,
                        verbose_name="Chave R2",
                    ),
                ),
                (
                    "r2_bucket",
                    models.CharField(
                        help_text="Nome do bucket onde está armazenado",
                        max_length=100,
                        verbose_name="Bucket R2",
                    ),
                ),
                ("is_folder", models.BooleanField(default=False, verbose_name="É Pasta?")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Se true, gera URLs públicas",
                        verbose_name="Público",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags separadas por vírgula",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="storage.storagefile",
                        verbose_name="Pasta Pai",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_files",
                        to="schools.school",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo",
                "verbose_name_plural": "Arquivos",
                "db_table": "storage_files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "parent_folder"], name="storage_fil_school__26de06_idx"
                    ),
                    models.Index(
                        fields=["school", "is_folder"], name="storage_fil_school__c58c40_idx"
                    ),
                    models.Index(fields=["r2_key"], name="storage_fil_r2_key_402e1f_idx"),
                    models.Index(fields=["created_by"], name="storage_fil_created_1bc16f_idx"),
                ],
            },
        ),
    ]
