# Generated by Django 5.2.7 on 2025-10-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('sobre', models.TextField()),
                ('niveis_ensino', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='eleveai.escola')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_agente', models.CharField(default='ativo', max_length=20)),
                ('interacoes_hoje', models.IntegerField(default=0)),
                ('documentos_upload', models.IntegerField(default=0)),
                ('faqs_criadas', models.IntegerField(default=0)),
                ('leads_capturados', models.IntegerField(default=0)),
                ('taxa_resolucao', models.IntegerField(default=0)),
                ('novos_hoje', models.IntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='eleveai.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_principal', models.EmailField(max_length=254)),
                ('telefone_principal', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('horario_aula', models.CharField(max_length=50)),
                ('diretor', models.CharField(max_length=255)),
                ('email_diretor', models.EmailField(max_length=254)),
                ('coordenador', models.CharField(max_length=255)),
                ('email_coordenador', models.EmailField(max_length=254)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='eleveai.escola')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('evento', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('feriado', '📌 Feriado'), ('prova', '📝 Prova/Avaliação'), ('formatura', '🎓 Formatura'), ('evento_cultural', '🎉 Evento Cultural')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eleveai.escola')),
            ],
            options={
                'verbose_name': 'Evento do Calendário',
                'verbose_name_plural': 'Eventos do Calendário',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=500)),
                ('resposta', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='eleveai.escola')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-criado_em'],
            },
        ),
    ]
