# Generated by Django 5.2.7 on 2025-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='niveis_ensino',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='escola',
            name='sobre',
            field=models.TextField(blank=True),
        ),
    ]
