# Generated by Django 5.2.7 on 2025-10-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0003_calendarioevento_usuario_contato_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='escola',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Escola', 'verbose_name_plural': 'Escolas'},
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contato', 'Em Contato'), ('qualificado', 'Qualificado'), ('conversao', 'Conversão'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('origem', models.CharField(choices=[('site', 'Site'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('ligacao', 'Ligação'), ('email', 'Email'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], default='site', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('interesses', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contatado_em', models.DateTimeField(blank=True, null=True)),
                ('convertido_em', models.DateTimeField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='eleveai.escola')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['escola', 'status'], name='eleveai_lea_escola__90b473_idx'), models.Index(fields=['criado_em'], name='eleveai_lea_criado__68b720_idx')],
            },
        ),
    ]
