# Generated by Django 5.2.7 on 2025-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0004_alter_contato_options_alter_dashboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='resposta',
            field=models.TextField(blank=True),
        ),
    ]
