# Generated by Django 5.2.7 on 2025-10-23 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0005_alter_faq_resposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Contato Geral', 'verbose_name_plural': 'Contatos Gerais'},
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='email_coordenador',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='coordenador',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='telefone_principal',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email_diretor',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email_principal',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='horario_aula',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='contato',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='origem',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('site', 'Site'), ('telefone', 'Telefone'), ('presencial', 'Presencial'), ('email', 'Email'), ('indicacao', 'Indicação')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='contato',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='contato',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contato',
            name='ultima_interacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_gerais', to='eleveai.escola'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_gerais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['escola', 'status'], name='eleveai_con_escola__b35ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['criado_em'], name='eleveai_con_criado__9fe5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['email'], name='eleveai_con_email_c57bee_idx'),
        ),
    ]
