# Generated by Django 5.2.7 on 2025-10-23 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0007_alter_contato_email_alter_contato_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='eleveai.escola'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to=settings.AUTH_USER_MODEL),
        ),
    ]
