# Generated by Django 5.2.7 on 2025-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0008_alter_contato_escola_alter_contato_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='token_mensagens',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
