# Generated by Django 5.2.7 on 2025-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0009_escola_token_mensagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='token_mensagens',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
