# Generated by Django 5.2.7 on 2025-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleveai', '0011_perfilusuario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='perfilusuario',
            new_name='eleveai_per_escola__f1f55f_idx',
            old_name='eleveai_per_escola__idx',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(help_text='CNPJ da escola (só superuser pode alterar)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome_escola',
            field=models.CharField(help_text='Nome da escola (só superuser pode alterar)', max_length=255),
        ),
        migrations.AlterField(
            model_name='escola',
            name='token_mensagens',
            field=models.CharField(blank=True, help_text='Token para mensagens (só superuser pode alterar)', max_length=40),
        ),
    ]
